runtime: go115

# app.yaml is supposed to be in the same directory as go.mod.
main: appengine

# Support using App Engine bundled services (e.g. memcache).
app_engine_apis: true

handlers:
- url: /(eval|purge|summarize)
  script: auto
  secure: always
  login: admin
- url: /(|query|report)
  script: auto
  secure: always
