application: home
version: 1
runtime: go
api_version: go1

builtins:
- remote_api: on

handlers:
- url: /summarize
  script: _go_app
  secure: always
  login: admin
- url: /.*
  script: _go_app
  secure: always
