runtime: go111

# TODO: This causes an error:
# ERROR: (gcloud.app.deploy) INVALID_ARGUMENT: script field for handler
# '/_ah/remote_api(/.*)?' must be set to 'auto' for runtime go112.
#builtins:
#- remote_api: on

handlers:
- url: /(eval|purge|summarize)
  script: auto
  secure: always
  login: admin
- url: /(|query|report)
  script: auto
  secure: always
