// Copyright 2017 Daniel Erat <dan@erat.org>
// All rights reserved.

package main

const (
	// Should tests be verbose?
	testVerbose = false

	// Names of samples generated by the collector.
	samplePingFailed          = "ping_failed"
	samplePingMin             = "ping_min"
	samplePingAvg             = "ping_avg"
	samplePingMax             = "ping_max"
	samplePingPacketLoss      = "ping_packet_loss"
	samplePowerOnLine         = "power_on_line"
	samplePowerLineVoltage    = "power_line_voltage"
	samplePowerLoadPercent    = "power_load_percent"
	samplePowerBatteryPercent = "power_battery_percent"
)
