// Copyright 2017 Daniel Erat <dan@erat.org>
// All rights reserved.

package collector

const (
	// Should tests be verbose?
	testVerbose = false

	// Names of samples generated by the collector.
	samplePingFailed     = "ping_failed"
	samplePingMin        = "ping_min"
	samplePingAvg        = "ping_avg"
	samplePingMax        = "ping_max"
	samplePingPacketLoss = "ping_packet_loss"
)
